# Generated by Django 3.0.7 on 2020-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200726_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
